<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />


<ul>
	<li><a href="facebook.com" class="nav-link"><i class="fab fa-facebook-f"></i></a></li>
	<li><a href="twitter.com" class="nav-link"><i class="fab fa-twitter"></i></a></li>
	<li><a href="https://plus.google.com/" class="nav-link"><i class="fab fa-google-plus-g"></i></a></li>
	<li><a href="pinterest.com" class="nav-link"><i class="fab fa-pinterest-p"></i></a></li>
	<li><a href="instagram.com" class="nav-link"><i class="fab fa-instagram"></i></a></li>
</ul>