<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2 style="text-align: center; font-size: 24px; font-weight: bold;">_____________RELATED PRODUCTS_____________</h2>
    <p style="color: #808080; text-align: center;">Top seller in the week</p>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="row">
                    <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="Chicago" style="width:100%;">

                </div>
            </div>

            <div class="item">
                <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="Chicago" style="width:100%;">
            </div>

            <div class="item">
                <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="New york" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>


<div class="container">
    <h2 style="text-align: center; font-size: 24px; font-weight: bold;">_____________RELATED PRODUCTS_____________</h2>
    <p style="color: #808080; text-align: center;">Top seller in the week</p>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="row">
                    <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="Chicago" style="width:100%;">

                </div>
            </div>

            <div class="item">
                <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="Chicago" style="width:100%;">
            </div>

            <div class="item">
                <img src="http://localhost:81/magento/pub/media/logo/default/product-detail-1_3.png" alt="New york" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>


<div class="container-fluid" id="footer">
    <div class="row">
        <div class="col-md-3">
            <div class="text-footer">
                <span class="fa fa-plane"></span>
                <span class="text">
                    <h3>FREESHIPPING</h3>
                    <p>Freeshipping all us</p>
                </span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="text-footer">
                <span class="fa fa-plane"></span>
                <span class="text">
                    <h3>SUPPORT 24/7</h3>
                    <p>Freeshipping all us</p>
                </span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="text-footer">
                <span class="fa fa-plane"></span>
                <span class="text">
                    <h3>30 DAY RETURN </h3>
                    <p>Freeshipping all us</p>
                </span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="text-footer">
                <span class="fa fa-plane"></span>
                <span class="text">
                    <h3>Payment 100% Secure</h3>
                    <p>Freeshipping all us</p>
                </span>
            </div>
            <div>
                <ul>
                    <li><span class="fa fa-facebook"></span></li>
                </ul>
            </div>
        </div>


    </div>
</div>



</body>
</html>

<style>
    #footer {
        /*background-color:red;*/
        height: 40px;
        width: 100%;
    }
</style>